server:
  port: 8089

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: STUDENTMICROSERVICES
          uri: lb://STUDENTMICROSERVICES
          predicates:
            - Path=/student/**
        - id: SCHOOLMICROSERVICES
          uri: lb://SCHOOLMICROSERVICES
          predicates:
            - Path=/school/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost